markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 2

safe: false

#站点基础配置
title: 斌-bin-
subTitle: 斌-bin- 's blog
description: 这是 斌斌 的博客，它是基于 Jekyll 搭建起来的。在这里，不仅仅是用来快速记录工作，学习，生活的一点一滴的地方，更是 斌斌 对 Jekyll 的学习和使用的一次有意义的实践。
url: http://127.0.0.1:4000
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 姓名大作战
    url: /fight/app/fight/index.html
  - text: 关于我
    url: /contact.html
  - text: 图片展示
    url: /pic/index.html


#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1
  - class: fa-facebook
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1
  - class: fa-github
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1
  - class: fa-weibo
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1
  - class: fa-renren
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1
  - class: fa-pinterest
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1
  - class: fa-twitter
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1
  - class: fa-rss
    url: http://www.weibo.com/2090605973/profile?topnav=1&wvr=5&user=1

#作者信息
author:
  link: 
  img: 

#评论信息
disqus:
  config: false
  id: 

duoshuo:
  config: false
  id: 